# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://babric.github.io/develop/
	minecraft_version=a1.1.2_01
	yarn_mappings=a1.1.2_01+build.41
	loader_version=0.15.6-babric.1

# Mod Properties
	mod_version = 1.0.0
	maven_group = com.floofyplasma
	archives_base_name = alpha-skygrid
